In [6]:
from qllm import LinearQuantizer
from qllm.utils import quantization_error
import torch 

In [2]:
# sample tensor
test_tensor = torch.randn((4, 4))
test_tensor


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "e:\dev\qllm\.venv\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "e:\dev\qllm\.venv\lib\site-pack

tensor([[-6.6477e-01,  1.9249e-02, -1.4870e+00,  8.5367e-01],
        [ 3.3279e-04,  1.6828e+00,  4.0892e-01,  2.2891e+00],
        [ 7.7625e-02, -2.7035e-01, -5.5813e-01,  1.3945e+00],
        [ 1.4665e+00, -3.1435e-02, -5.4522e-01,  1.0112e-01]])

In [3]:
scale = LinearQuantizer.get_symmetric_scale(test_tensor)
print(f"Scale: {scale}")

Scale: 0.018024029694204257


In [4]:
# quantize tensor
linear_q = LinearQuantizer(
    test_tensor,
    scale=scale,
    zero_point=0,
)
q_tensor = linear_q.quantize()
q_tensor

tensor([[-37,   1, -82,  47],
        [  0,  93,  23, 127],
        [  4, -15, -31,  77],
        [ 81,  -2, -30,   6]], dtype=torch.int8)

In [5]:
# dequantize tensor
dequantized_tensor = linear_q.dequantize(q_tensor)
dequantized_tensor

tensor([[-0.6669,  0.0180, -1.4780,  0.8471],
        [ 0.0000,  1.6762,  0.4146,  2.2891],
        [ 0.0721, -0.2704, -0.5587,  1.3879],
        [ 1.4599, -0.0360, -0.5407,  0.1081]])

In [10]:
quantization_error(test_tensor, dequantized_tensor)

tensor(2.5837e-05)

In [1]:
from qllm.linear_quantization import W8A16LLqllm

module = W8A16LLqllm(4, 8)


In [2]:
print("Weights before:\n", module.int8_weights)

Weights before:
 tensor([[ -50,  -71,   69,  -54],
        [ -74,    7,   68,  -55],
        [  -2,   64,  -76,   18],
        [ -68,  -93,  -63,  -31],
        [  26,   89, -115,  -19],
        [  25,  -62,  107,  -15],
        [ 120,   11,   37,   52],
        [-118,  106,  112,  -51]], dtype=torch.int8)


In [4]:
import torch 
dummy_hidden_states = torch.randn(1, 6, 16)
module(dummy_hidden_states).shape


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "e:\dev\qllm\.venv\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "e:\dev\qllm\.venv\lib\site-pack

RuntimeError: mat1 and mat2 shapes cannot be multiplied (6x16 and 4x8)